package org.metadatacenter.cedar.rest;

import io.modelcontextprotocol.json.McpJsonDefaults;
import io.modelcontextprotocol.server.McpServer;
import io.modelcontextprotocol.server.McpSyncServer;
import io.modelcontextprotocol.server.McpSyncServerExchange;
import io.modelcontextprotocol.server.transport.StdioServerTransportProvider;
import io.modelcontextprotocol.spec.McpSchema;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * MCP server that manages CEDAR artifacts through the CEDAR resource-server REST API. The I/O
 * counterpart to {@code cedar-artifact-mcp}: it persists artifacts to, and fetches them from, a
 * live CEDAR server.
 *
 * <p>CRUD tools ({@code get / create / update / delete} × template/element/field/instance) are
 * generated by {@link ArtifactCrudTools}; {@code validate_artifact} wraps the server's
 * {@code /command/validate}. The HTTP connection and API key come from the environment
 * ({@code CEDAR_BASE_URL}, {@code CEDAR_API_KEY}; see {@link CedarConfig}). See {@code DESIGN.md}
 * and {@code ROADMAP.md}.
 */
public final class CedarRestMcpServer
{
  private static final String SERVER_NAME = "cedar-rest-mcp";
  private static final String SERVER_VERSION = "0.1.0";

  private CedarRestMcpServer() {}

  public static void main(String[] args) throws InterruptedException
  {
    CedarConfig config = CedarConfig.fromEnv();
    CedarHttp http = new DefaultCedarHttp(config);

    var spec = McpServer.sync(new StdioServerTransportProvider(McpJsonDefaults.getMapper()))
        .serverInfo(SERVER_NAME, SERVER_VERSION)
        .capabilities(McpSchema.ServerCapabilities.builder().tools(true).build())
        .toolCall(pingTool(), CedarRestMcpServer::pingHandler);

    for (ArtifactCrudTools.RegisteredTool registered : ArtifactCrudTools.all(http))
      spec.toolCall(registered.tool(), registered.handler());

    ArtifactCrudTools.RegisteredTool validate = ValidateArtifactTool.create(http);
    spec.toolCall(validate.tool(), validate.handler());

    McpSyncServer server = spec.build();

    // Stdio transport reads from System.in on a background thread; keep main alive until the JVM
    // is interrupted (typically when the parent process closes stdin).
    Runtime.getRuntime().addShutdownHook(new Thread(server::close));
    Thread.currentThread().join();
  }

  // ---------------------------------------------------------------- ping

  private static McpSchema.Tool pingTool()
  {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("message", Map.of("type", "string", "description", "Arbitrary string to echo back."));

    McpSchema.JsonSchema schema = new McpSchema.JsonSchema(
        "object", properties, List.of("message"), Boolean.FALSE, null, null);

    return McpSchema.Tool.builder()
        .name("ping")
        .title("ping")
        .description("Echoes the supplied message. Verifies the MCP server is reachable. Does not "
            + "contact the CEDAR server.")
        .inputSchema(schema)
        .build();
  }

  private static McpSchema.CallToolResult pingHandler(
      McpSyncServerExchange exchange, McpSchema.CallToolRequest request)
  {
    Object raw = request.arguments() == null ? null : request.arguments().get("message");
    String message = raw == null ? "" : raw.toString();

    return McpSchema.CallToolResult.builder()
        .content(List.of(new McpSchema.TextContent(null, "pong: " + message)))
        .isError(false)
        .build();
  }
}
